Fixed missing needs_migration?
NoMethodError: undefined method `needs_migration?' for ActiveRecord::Migrator:Class
/builds/gitlab-org/gitlab-ee/lib/gitlab/current_settings.rb:48:in `uncached_application_settings'